jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Maven Build
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        run: |
          docker build -t $env:DOCKER_USERNAME/$env:IMAGE_NAME:latest .
          docker push $env:DOCKER_USERNAME/$env:IMAGE_NAME:latest

      - name: Deploy to Minikube
        shell: powershell
        run: |
          kubectl config use-context minikube
          kubectl apply -f k8s/books-deployment.yaml
          kubectl apply -f k8s/books-service.yaml
          kubectl rollout status deployment/books-deployment
