name: Books Service CI/CD

on:
  push:
    branches: [main]

env:
  DOCKER_USERNAME: rbutechnologies
  IMAGE_NAME: books-service

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Docker build & push
        run: |
          docker build -t $DOCKER_USERNAME/$IMAGE_NAME:latest .
          docker push $DOCKER_USERNAME/$IMAGE_NAME:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to Minikube
        run: |
          kubectl config use-context minikube
          kubectl apply -f k8s/books-deployment.yaml
          kubectl apply -f k8s/books-service.yaml
          kubectl rollout status deployment/books-deployment
